// improved-compile-route.js
const express = require("express");
const fs = require("fs");
const path = require("path");
const { exec, spawn } = require("child_process");
const { v4: uuid } = require("uuid");
const rimraf = require("rimraf"); // optional: npm i rimraf

const router = express.Router();

function safeJoin(base, target) {
  const targetPath = path.normalize(path.join(base, target));
  if (!targetPath.startsWith(base)) throw new Error("Invalid file path");
  return targetPath;
}

router.post("/compile-cpp", async (req, res) => {
  const id = uuid();
  const baseDir = path.join("/tmp", id);

  try {
    // Create working directory
    fs.mkdirSync(baseDir, { recursive: true });

    // Validate payload
    const files = req.body.files || {};
    const buildSolution = !!req.body.buildSolution;
    const solutionName = req.body.solution || null;

    // If user asked to build a Visual Studio solution, return guidance (server is Linux)
    if (buildSolution) {
      // If you have a Windows build agent or msbuild container, you can implement it here.
      return res.json({
        error: "Server cannot build Visual Studio .sln on this host. " +
               "To build .sln files, run MSBuild on Windows or use a Windows build container. " +
               "Alternatively, convert the project to CMake for cross-platform builds."
      });
    }

    // Write files to disk, creating directories as needed
    for (const [name, content] of Object.entries(files)) {
      // Normalize and prevent path traversal
      const dest = safeJoin(baseDir, name);
      const dir = path.dirname(dest);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(dest, content, "utf8");
    }

    // Collect .cpp files (absolute paths)
    const cppFiles = Object.keys(files).filter(f => f.endsWith(".cpp"));
    let compileFiles = cppFiles.map(f => safeJoin(baseDir, f));

    // If no .cpp files, create an autogenerated runner that lists files
    let autogenName = null;
    if (compileFiles.length === 0) {
      autogenName = "__autogen_main.cpp";
      const autogenPath = path.join(baseDir, autogenName);
      const fileList = Object.keys(files).map(p => `  std::cout << "${p}" << std::endl;`).join("\n");
      const autogenContent = `#include <iostream>\nint main(){\n  std::cout << "No main() found. Autogenerated runner." << std::endl;\n${fileList}\n  return 0;\n}\n`;
      fs.writeFileSync(autogenPath, autogenContent, "utf8");
      compileFiles = [autogenPath];
    }

    // Build command
    const exeName = process.platform === "win32" ? "app.exe" : "app.out";
    const exePath = path.join(baseDir, exeName);
    const compileArgs = ["-std=c++17", "-O2", "-Wall", "-Wextra", "-o", exePath, ...compileFiles];

    // Use spawn for better control and streaming
    const compiler = spawn("g++", compileArgs, { cwd: baseDir, env: process.env });

    let compileStdout = "";
    let compileStderr = "";
    let compileTimedOut = false;
    const compileTimeout = setTimeout(() => {
      compileTimedOut = true;
      compiler.kill("SIGKILL");
    }, 30_000); // 30s compile timeout

    compiler.stdout.on("data", (d) => { compileStdout += d.toString(); });
    compiler.stderr.on("data", (d) => { compileStderr += d.toString(); });

    compiler.on("close", (code, signal) => {
      clearTimeout(compileTimeout);

      if (compileTimedOut) {
        // cleanup
        try { rimraf.sync(baseDir); } catch(e){}
        return res.json({ error: "Compilation timed out." });
      }

      if (code !== 0) {
        // compilation failed
        try { rimraf.sync(baseDir); } catch(e){}
        return res.json({
          compile: {
            success: false,
            exitCode: code,
            stdout: compileStdout,
            stderr: compileStderr
          },
          error: compileStderr || "Compilation failed"
        });
      }

      // Compilation succeeded — run the binary with a timeout
      const runner = spawn(exePath, [], { cwd: baseDir, env: process.env, stdio: ["ignore", "pipe", "pipe"] });
      let runOut = "";
      let runErr = "";
      let runTimedOut = false;
      const runTimeout = setTimeout(() => {
        runTimedOut = true;
        runner.kill("SIGKILL");
      }, 10_000); // 10s run timeout

      runner.stdout.on("data", (d) => { runOut += d.toString(); });
      runner.stderr.on("data", (d) => { runErr += d.toString(); });

      runner.on("close", (runCode, runSignal) => {
        clearTimeout(runTimeout);
        // cleanup
        try { rimraf.sync(baseDir); } catch(e){}

        if (runTimedOut) {
          return res.json({
            compile: { success: true, exitCode: 0, stdout: compileStdout, stderr: compileStderr },
            run: { success: false, exitCode: null, stdout: runOut, stderr: "Execution timed out." },
            error: "Execution timed out."
          });
        }

        if (runCode !== 0) {
          return res.json({
            compile: { success: true, exitCode: 0, stdout: compileStdout, stderr: compileStderr },
            run: { success: false, exitCode: runCode, stdout: runOut, stderr: runErr },
            error: runErr || "Program exited with non-zero code"
          });
        }

        // success
        return res.json({
          compile: { success: true, exitCode: 0, stdout: compileStdout, stderr: compileStderr },
          run: { success: true, exitCode: 0, stdout: runOut, stderr: runErr }
        });
      });
    });

  } catch (e) {
    // cleanup on unexpected error
    try { rimraf.sync(baseDir); } catch(err){}
    return res.json({ error: e.message || String(e) });
  }
});

module.exports = router;
